language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
  - dotnet restore ./EFSqlTranslator.sln
  - dotnet build ./EFSqlTranslator.sln
  - dotnet test ./EFSqlTranslator.Tests/EFSqlTranslator.Tests.csproj
